// <auto-generated />
using System;
using FinanceOverview.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceOverview.Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20250305000000_AddMerchantRulesAndCategories")]
partial class AddMerchantRulesAndCategories
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0");

        modelBuilder.Entity("FinanceOverview.Api.Models.Category", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("Categories");
            });

        modelBuilder.Entity("FinanceOverview.Api.Models.ImportBatch", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("ExtractedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("OriginalFileName")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("ParserKey")
                    .HasColumnType("TEXT");

                b.Property<string>("Sha256Hash")
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("StatementMonth")
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("StorageKey")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateTime>("UploadedAt")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("StatementMonth", "Sha256Hash")
                    .IsUnique();

                b.ToTable("ImportBatches");
            });

        modelBuilder.Entity("FinanceOverview.Api.Models.MerchantRule", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<int?>("CategoryId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAtUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("MatchType")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("NormalizedMerchant")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Pattern")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Priority")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(100);

                b.HasKey("Id");

                b.HasIndex("CategoryId");

                b.ToTable("MerchantRules");
            });

        modelBuilder.Entity("FinanceOverview.Api.Models.StagedTransaction", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<decimal>("Amount")
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("BookingDate")
                    .HasColumnType("TEXT");

                b.Property<string>("Currency")
                    .HasColumnType("TEXT");

                b.Property<int>("ImportBatchId")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsApproved")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER")
                    .HasDefaultValue(false);

                b.Property<string>("RawDescription")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("RowIndex")
                    .HasColumnType("INTEGER");

                b.Property<decimal?>("RunningBalance")
                    .HasColumnType("TEXT");

                b.Property<DateOnly?>("ValueDate")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ImportBatchId");

                b.ToTable("StagedTransactions");
            });

        modelBuilder.Entity("FinanceOverview.Api.Models.Transaction", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<decimal>("Amount")
                    .HasColumnType("TEXT");

                b.Property<decimal?>("Balance")
                    .HasColumnType("TEXT");

                b.Property<int?>("CategoryId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<DateOnly>("Date")
                    .HasColumnType("TEXT");

                b.Property<int?>("ImportBatchId")
                    .HasColumnType("INTEGER");

                b.Property<string>("Merchant")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("MerchantNormalized")
                    .HasColumnType("TEXT");

                b.Property<string>("RawDescription")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("RowFingerprint")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("CategoryId");

                b.HasIndex("ImportBatchId", "RowFingerprint")
                    .IsUnique()
                    .HasFilter("ImportBatchId IS NOT NULL AND RowFingerprint IS NOT NULL");

                b.ToTable("Transactions");
            });

        modelBuilder.Entity("FinanceOverview.Api.Models.MerchantRule", b =>
            {
                b.HasOne("FinanceOverview.Api.Models.Category", "Category")
                    .WithMany()
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.Navigation("Category");
            });

        modelBuilder.Entity("FinanceOverview.Api.Models.StagedTransaction", b =>
            {
                b.HasOne("FinanceOverview.Api.Models.ImportBatch", "ImportBatch")
                    .WithMany("StagedTransactions")
                    .HasForeignKey("ImportBatchId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("ImportBatch");
            });

        modelBuilder.Entity("FinanceOverview.Api.Models.Transaction", b =>
            {
                b.HasOne("FinanceOverview.Api.Models.Category", "Category")
                    .WithMany()
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.Navigation("Category");
            });

        modelBuilder.Entity("FinanceOverview.Api.Models.ImportBatch", b =>
            {
                b.Navigation("StagedTransactions");
            });
    }
}
